# Generated by Django 2.1 on 2018-09-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
